### PR TITLE
Localization files

### PR DESCRIPTION
**Pull request by Linnnnnna**
There's some issues i don't know how to fix, Sorry.

### CODE REVIEW

**Comment by steviegt6** [comment]
Thank you! Will get to reviewing this later today (in a couple of hours, but no promises). @ThatDamnPineapple could you review this as well? Would let to get some more input.

@Linnnnnna what issues were you unable to fix? From a brief overview, I saw some commented localization code with the Boss Checklist Mod.Call, is that the only issue? Is there any more?

**Comment by Linnnnnna** [comment]
> 

System.ArgumentException: Found whitespace in your key name (use quotes to include). At line 304, column 25
   at Hjson.HjsonReader.readKeyName()
   at Hjson.HjsonReader.ReadCore(Boolean objectWithoutBraces)
   at Hjson.HjsonReader.ReadCore(Boolean objectWithoutBraces)
   at Hjson.HjsonReader.ReadCore(Boolean objectWithoutBraces)
   at Hjson.HjsonReader.ReadCore(Boolean objectWithoutBraces)
   at Hjson.HjsonReader.Read()
   at Hjson.HjsonValue.load(TextReader textReader, IJsonReader jsonReader, HjsonOptions options)
   at Hjson.HjsonValue.Load(TextReader textReader, IJsonReader jsonReader)
   at Hjson.HjsonValue.Parse(String hjsonString)
   at Terraria.ModLoader.LocalizationLoader.AutoloadTranslations(Mod mod, Dictionary`2 modTranslationDictionary) in tModLoader\Terraria\ModLoader\LocalizationLoader.cs:line 216
   at Terraria.ModLoader.LocalizationLoader.Autoload(Mod mod) in tModLoader\Terraria\ModLoader\LocalizationLoader.cs:line 59
   at Terraria.ModLoader.Mod.Autoload() in tModLoader\Terraria\ModLoader\Mod.Internals.cs:line 52
   at Terraria.ModLoader.ModContent.<>c.<Load>b__42_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 316
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 382
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 310
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 124
[07:29:35.286] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: CrystiliumMod

**Comment by Linnnnnna** [comment]
> Thank you! Will get to reviewing this later today (in a couple of hours, but no promises). @ThatDamnPineapple could you review this as well? Would let to get some more input.
> 
> @Linnnnnna what issues were you unable to fix? From a brief overview, I saw some commented localization code with the Boss Checklist Mod.Call, is that the only issue? Is there any more?

except WorldGeneration, all done(maybe)
c

**Comment by steviegt6** [comment]
You can do World Gen stuff in a follow-up PR.

**Pull request merged**
